[package]
name = "bix"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version="4.5", features=["derive"] }

[profile.release]
strip = true
lto = true
opt-level = "z"
codegen-units = 1
panic = "abort"
