name: Release Bix

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            ext: ""
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            ext: ".exe"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build release
        run: cargo build --release --target ${{ matrix.target }}

      - name: Package Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir dist
          tar czvf dist/bix-${{ matrix.target }}.tar.gz -C target/${{ matrix.target }}/release bix

      - name: Package Windows
        if: matrix.os == 'windows-latest'
        run: |
          mkdir dist
          7z a dist/bix-${{ matrix.target }}.zip ./target/${{ matrix.target }}/release/bix.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bix-${{ matrix.target }}
          path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/*.tar.gz,artifacts/**/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
